### ISSUE TITLE
Could you upload and compile packages that run directly?

### ISSUE THREAD

**Issue by laketop** [fagnercarvalho/prometheus-iotdb-exporter#2]
Could you upload and compile packages that run directly?Thank you very much

**Comment by fagnercarvalho** [comment]
Sure! I will work on this during this week.

**Comment by fagnercarvalho** [comment]
This is done, you should see the executables for all major OSes in the latest release at https://github.com/fagnercarvalho/prometheus-iotdb-exporter/releases/tag/v1.1.

Let me know if you need anything else, have a good weekend!

**Comment by laketop** [comment]
> This is done, you should see the executables for all major OSes in the latest release at https://github.com/fagnercarvalho/prometheus-iotdb-exporter/releases/tag/v1.1.
> 
> Let me know if you need anything else, have a good weekend!



> 完成此操作后，您应该在https://github.com/fagnercarvalho/prometheus-iotdb-exporter/releases/tag/v1.1的最新版本中看到所有主要OS的可执行文件。
> 
> 如果您还有其他需要，请让我度过一个愉快的周末！



> This is done, you should see the executables for all major OSes in the latest release at https://github.com/fagnercarvalho/prometheus-iotdb-exporter/releases/tag/v1.1.
> 
> Let me know if you need anything else, have a good weekend!

Which one does the dashboard use?

**Comment by laketop** [comment]
> This is done, you should see the executables for all major OSes in the latest release at https://github.com/fagnercarvalho/prometheus-iotdb-exporter/releases/tag/v1.1.
> 
> Let me know if you need anything else, have a good weekend!

Which one does the dashboard use?

**Comment by fagnercarvalho** [comment]
> > This is done, you should see the executables for all major OSes in the latest release at https://github.com/fagnercarvalho/prometheus-iotdb-exporter/releases/tag/v1.1.
> > Let me know if you need anything else, have a good weekend!
> 
> Which one does the dashboard use?

Which dashboard are you talking about?

**Comment by laketop** [comment]
> Which dashboard are you talking about?

grafana dashboard

**Comment by fagnercarvalho** [comment]
> > Which dashboard are you talking about?
> 
> grafana dashboard

If you are talking about [this one](https://github.com/apache/iotdb/tree/master/grafana), this is not using the exporter but its own implementation.

**Comment by laketop** [comment]
> If you are talking about [this one](https://github.com/apache/iotdb/tree/master/grafana), this is not using the exporter but its own implementation.

I want to show the data collected by iotdb_exporter on Grafana

**Comment by fagnercarvalho** [comment]
> > If you are talking about [this one](https://github.com/apache/iotdb/tree/master/grafana), this is not using the exporter but its own implementation.
> 
> I want to show the data collected by iotdb_exporter on Grafana

Oh, got it, you want this exporter in a Grafana dashboard. I added issue https://github.com/fagnercarvalho/prometheus-iotdb-exporter/issues/3 to track this change, let's talk about this there.

**Comment by laketop** [comment]
> Oh, got it, you want this exporter in a Grafana dashboard. I added issue #3 to track this change, let's talk about this there.

Cool, Can this iotdb_exporter monitor the running status of iotdb?

**Comment by fagnercarvalho** [comment]
> > Oh, got it, you want this exporter in a Grafana dashboard. I added issue #3 to track this change, let's talk about this there.
> 
> Cool, Can this iotdb_exporter monitor the running status of iotdb?

You mean something like a health check? If the IoTDB instance is offline or unreachable we will return a `iotdb_connection_error` metric with some information about why the connection failed. This follows the [recommended strategy for handling failed metric collection according to Prometheus](https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes).
